### ISSUE TITLE
downloads.txt无法显示中文名

### ISSUE THREAD

**Issue by iamvicliu** [Echowxsy/CMPEDUDownload#10]
https://cmpebooks.s3.cn-north-1.amazonaws.com.cn/books/4/978-7-111-49107-1_1-2/PDF/978-7-111-49107-1_1-2_2.pdf
	referer=https://cmpebooks.s3.cn-north-1.amazonaws.com.cn/pdfReader/generic/build/pdf.worker.js
	out=downloads/ZC08-姹借溅鎶€鏈垱鏂颁笌鐮斿彂绯诲垪涓涗功/姹借溅杞﹁韩鍣０涓庢尟鍔ㄦ帶鍒?pdf

**Comment by BaldStrong** [comment]
网站被爬崩了！

**Comment by lizhirui** [comment]
把downloads.txt转码为utf-8即可
