### ISSUE TITLE
下载文件文件名乱码

### ISSUE THREAD

**Issue by Reverssss** [Echowxsy/CMPEDUDownload#12]
[DL:11MiB][#0c4902 30MiB/38MiB(80%)][#174d5d 15MiB/96MiB(16%)][#677513 24MiB/71MiB(34%)][#d2f74f 13MiB/53MiB(25%)][#ee
02/03 22:38:56 [NOTICE] Download complete: D:/aria2/downloads/AA08-����һ�廯/��ҵ������Ӧ�ü�������.pdf

**Comment by lizhirui** [comment]
把downloads.txt转码为utf-8即可
