### ISSUE TITLE
可以下载吗？

### ISSUE THREAD

**Issue by xmdt** [Echowxsy/CMPEDUDownload#13]
我使用windows版本的aria2c，无法下载呀~

**Comment by echowxsy** [comment]
具体是什么问题呢？

**Comment by xmdt** [comment]
> 具体是什么问题呢？

02/06 12:03:47 [ERROR] CUID#7 - Download aborted. URI=https://cmpebooks.s3.cn-north-1.amazonaws.com.cn/books/5/978-7-111-55094-5_1-1/PDF/978-7-111-55094-5_1-1_2.pdf
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://cmpebooks.s3.cn-north-1.amazonaws.com.cn/books/5/978-7-111-55094-5_1-1/PDF/978-7-111-55094-5_1-1_2.pdf
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

你自己现在跑一下脚本试试？

**Comment by echowxsy** [comment]
目前机械工业出版社正在对服务器进行扩容升级，暂停了服务的访问。
