### ISSUE TITLE
发现一个问题：下载3本就自动结束了

### ISSUE THREAD

**Issue by Youngstack** [Echowxsy/CMPEDUDownload#4]
问题：限定类目为【AC02 计算机科学(11)】，固定下载3本书之后就停止了，是什么原因呢~求助

**Comment by echowxsy** [comment]
> 问题：限定类目为【AC02 计算机科学(11)】，固定下载3本书之后就停止了，是什么原因呢~求助

是这样的，图书有两类，一类是PDF文件，一类是xhtml文件（EPUB），目前只实现了PDF的下载，这个目录下只有三本是PDF类型的。

**Comment by tddey01** [comment]
[1] 1314
[root@spider CMPEDUDownload]# Traceback (most recent call last):
  File "download.py", line 49, in <module>
    main()
  File "download.py", line 45, in main
    print("%s\n\treferer=%s\n\tout=%s" % (pdf_link, referer, saved_path))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 227-230: ordinal not in range(128)

**Comment by Youngstack** [comment]
> > 问题：限定类目为【AC02 计算机科学(11)】，固定下载3本书之后就停止了，是什么原因呢~求助
> 
> 是这样的，图书有两类，一类是PDF文件，一类是xhtml文件（EPUB），目前只实现了PDF的下载，这个目录下只有三本是PDF类型的。

明白了~ 感谢
