### ISSUE TITLE
服务器都崩了

### ISSUE THREAD

**Issue by HelloLingC** [Echowxsy/CMPEDUDownload#6]
其实没必要这么夸张吧，盗版电子书一搜一大堆非要爬这个 = =

{"success":false,"code":"common_0001","mess":"对不起，系统异常了，请联系管理员!","module":null,"otherResult":null}

**Comment by HelloLingC** [comment]
看看源码图一乐乎就行啦，一大堆人一起爬肯定扛不住啊

**Comment by echowxsy** [comment]
好好看看源码告诉我这样子的请求有压力吗‘？
