### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tddey01** [Echowxsy/CMPEDUDownload#7]
[1] 1314
[root@spider CMPEDUDownload]# Traceback (most recent call last):
  File "download.py", line 49, in <module>
    main()
  File "download.py", line 45, in main
    print("%s\n\treferer=%s\n\tout=%s" % (pdf_link, referer, saved_path))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 227-230: ordinal not in range(128)

**Comment by echowxsy** [comment]
貌似是编码问题，发生错误时处理的字符串是什么？
